### ISSUE TITLE
ImportError: cannot import name 'KalmanFilter' from 'kalmanfilter' (unknown location)

### ISSUE THREAD

**Issue by kesslerf** [Xylambda/kalmanfilter#20]
Hello,
I tried to import the KalmanFilter-function to run your example, but I got the error in the title.

I used 
git clone https://github.com/Xylambda/kalmanfilter.git
pip install kalmanfilter/.

to install the package and run it on the following specs:
Windows 10
Python 3.9.2

Any idea why it didnt work?

**Comment by Xylambda** [comment]
Hi, @kesslerf 

thanks for opening the issue. 

It seems a there is a problem with the installation, but I cannot confirm it with the info you provided.

Could you please provide a [MRE](https://stackoverflow.com/help/minimal-reproducible-example) with the complete error trace and the exact code you used.

Also, it would be useful to have the requirements of your environment. You can create a file with those requirements by redirecting the output of `pip freeze` command:

```python
>>> conda activate your_env
>>> pip freeze > env_requirements.txt
```

Thanks!

**Comment by kesslerf** [comment]
Thanks for coming back so fast.

My MRE would be the following:

I opened python (both spyder and command line)  and tipped
from kalmanfilter import KalmanFilter

requirements.txt
[env_requirements.txt](https://github.com/Xylambda/kalmanfilter/files/6364836/env_requirements.txt)

**Comment by Xylambda** [comment]
Hi,

it seems to be a bug. The name in the `setup` file [is not correctly set](https://github.com/Xylambda/kalmanfilter/blob/master/setup.py#L6). It should be `name='kalmanfilter'`

I will update it as soon as I can. Then, you will have to reinstall the library and restart the console:
```python
pip install kalmanfilter/. --force-reinstall
```

Thanks for finding the bug @kesslerf !

**Comment by kesslerf** [comment]
Happy to help even if its only finding bugs. Thanks for your response, looking forward to using it as soon as possible :)

**Comment by Xylambda** [comment]
Hi @kesslerf
the latest changes seem to have solve the problem
Thanks!

**Comment by kesslerf** [comment]
It is still not working for me, I am using Anaconda on Windows 10 (if that changes something):

Here is what I did (all in Terminal/Anaconda Prompt): 

Create a new environment
activate the new environment
conda install git
conda insta pip

git clone https://github.com/Xylambda/kalmanfilter.git
pip install kalmanfilter/.

python (python 3.9.4 starts)
from kalmanfilter import KalmanFilter

and that results in the same error again.

**Comment by Xylambda** [comment]
Hi @kesslerf 

apparently, I forgot to add the line `packages=find_packages(exclude=['tests', 'docs', 'examples', 'img']),` to the setup file. The library is not able to find the source folder and hence the bug.

I don't really understand why the CI/CD is passing (and it is also working on my Mac). Anyway, I will update and test the new change as soon as I can get a Windows VM.

Apologize for any inconvenience.

**Comment by kesslerf** [comment]
I would have to do the pip install kalmanfilter/. --force-reinstall again to get it working as intended now?

**Comment by Xylambda** [comment]
First, you should pull the latest changes to your local repo:
```bash
cd path_to_kalmanfilter_folder/
git pull
```

If you already are in package the folder:
```bash
pip install . 
```

then reinstalling again as you say.

I tested the latest changes on a Windows machine, so it should work properly now:
```python
$ python -c "import kalmanfilter as kf; print(kf)"
<module 'kalmanfilter' from 'D:\\Users\\aperez\\env\\test\\lib\\site-packages\\kalmanfilter\\__init__.py'>
```

**Comment by kesslerf** [comment]
Works perfectly now! Thank you for the fast response and the package in general, now the next thing is to fine-tune the parameters for our purpose.

**Comment by Xylambda** [comment]
Nice!

Just out of curiosity, may I ask in which field are you applying the Kalman Filter?

**Comment by kesslerf** [comment]
My Boss wants me to use it on a time series of a Ratio used in Remote Sensing to determine the change in vitality in trees. I actually do not know 100% if kalman filtering is the best for this, but as I already said, she is my boss ;D
